package com.cqm.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cqm.greendao.db.Banner;
import com.cqm.greendao.db.User;

import com.cqm.greendao.db.BannerDao;
import com.cqm.greendao.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BannerDao bannerDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerDaoConfig = daoConfigMap.get(BannerDao.class).clone();
        bannerDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bannerDao = new BannerDao(bannerDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Banner.class, bannerDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        bannerDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BannerDao getBannerDao() {
        return bannerDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
